### PR TITLE
Add missing allowed prop type

### PR DESCRIPTION
**Pull request by indygriffiths**
Found that without allowing `elementType` I'd get `Warning: Failed prop type: Invalid prop `RegisterComponent` supplied to `RegisterModal`.` when injecting this component.

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
That's a weird one. Can I ask what exactly you were injecting? I think `elementType` makes sense though.

Our JS linter is set to 100 char lines btw so the line will need to be broken up now. Also would you mind targetting this PR at `4.0` as a bug fix?

**Comment by indygriffiths** [comment]
Was injecting `RegisteredMFAMethodListField` by calling `Injector.component.registerMany` and including it, and then loading it via `loadComponent('RegisteredMFAMethodListField');`

**Comment by ScopeyNZ** [comment]
Linter is being cruel: 
image (Extra whitespace)

**Comment by NightJar** [comment]
Please also commit `dist` files @indygriffiths :)
https://travis-ci.com/silverstripe/silverstripe-mfa/jobs/226910568#L820

**Comment by indygriffiths** [comment]
> Please also commit `dist` files @indygriffiths :)
> https://travis-ci.com/silverstripe/silverstripe-mfa/jobs/226910568#L820

Any ideas when using Node 10.16.0 and running yarn?

```
    
    ERROR in ./client/src/bundles/bundle.scss
    Module build failed: ModuleBuildError: Module build failed: 
    @import 'variables';
    ^
          File to import not found or unreadable: variables.
          in /home/igriffiths/Sites/silverstripe-mfa/client/src/bundles/bundle.scss (line 2, column 1)
        at runLoaders (/home/igriffiths/Sites/silverstripe-mfa/node_modules/webpack/lib/NormalModule.js:192:19)
        at /home/igriffiths/Sites/silverstripe-mfa/node_modules/loader-runner/lib/LoaderRunner.js:367:11
        at /home/igriffiths/Sites/silverstripe-mfa/node_modules/loader-runner/lib/LoaderRunner.js:233:18
        at context.callback (/home/igriffiths/Sites/silverstripe-mfa/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
        at Object.asyncSassJobQueue.push [as callback] (/home/igriffiths/Sites/silverstripe-mfa/node_modules/sass-loader/lib/loader.js:55:13)
        at Object.done [as callback] (/home/igriffiths/Sites/silverstripe-mfa/node_modules/neo-async/async.js:8067:18)
        at options.error (/home/igriffiths/Sites/silverstripe-mfa/node_modules/node-sass/lib/index.js:294:32)
```

**Comment by robbieaverill** [comment]
For the 4.0 branch you need to also run `yarn install` in the admin module

**Comment by robbieaverill** [comment]
Needs a rebase now =(

**Comment by indygriffiths** [comment]
No idea why Github says that's conflicting, blew away my local branch, branched off from 4.0, redid the change, and then force pushed to my patch branch.

image

**Comment by robbieaverill** [comment]
Perhaps your remotes are not pointing at this repo? I've rebased for you =)

**Pull request merged**
