### PR TITLE
FIX Remove left margin on action items in MFA screens. They have right margins from admin now.

### PR DESCRIPTION
**Pull request by robbieaverill**

### CODE REVIEW

**Comment by Cheddam** [comment]
@robbieaverill Think you need to run a `yarn build` before we can merge this.

**Comment by robbieaverill** [comment]
Gah, I've done it so many times already

**Comment by robbieaverill** [comment]
Annoyingly we need to add this back in the admin itself...

**Comment by robbieaverill** [comment]
Follow up PR at https://github.com/silverstripe/silverstripe-mfa/pull/208

**Pull request merged**
