### PR TITLE
ENH Update translations

### PR DESCRIPTION
**Pull request by GuySartorelli**
Automated translations update generated using [silverstripe/tx-translator](https://github.com/silverstripe/silverstripe-tx-translator)

### CODE REVIEW

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Looks like a bunch of English "translations" have been added to the translation files

**Comment by GuySartorelli** [comment]
That's understandable. We did a i18ntextcollector run in CMS 5, then pushed strings to transifex there, then pulled them here.

**Comment by emteknetnz** [comment]
That shouldn't result in there being English "translations" showing up for languages like French

**Comment by GuySartorelli** [comment]
As discussed in person the problem is the english values being present in non-english locale files.

Closing - a new PR with the correct translations will be generated next time we run tx-translator after fixing https://github.com/silverstripe/silverstripe-tx-translator/issues/18

**Pull request closed without merging**
